#! /bin/sh

### BEGIN INIT INFO
# Provides:		packetbl
# Required-Start:	
# Required-Stop:	
# Default-Start:	2 3 4 5
# Default-Stop:	0 1 6
# Short-Description:	RBL client
### END INIT INFO

# Changed to get config files as follows:
# All of the following are INDIVIDUALLY used:
#   /etc/packetbl.conf
#   /etc/packetbl.d/*.conf
# Running MULTIPLE instances with different config files seems like
# rare use-case


BIN=/usr/bin/packetbl
# Don't worry about PID - assume systemd can take care of it
PID_PATH=/dev/null
ACTION=$1


get_config_files() {
    CONFIG_FILES=""
    local CONFIG_FILES_CANDIDATES=$(ls -1 etc/packetbl.conf etc/packetbl.d/*.conf 2>/dev/null)
    for f in $CONFIG_FILES_CANDIDATES
    do
        if [ -f "$f" ]; then
            CONFIG_FILES="${CONFIG_FILES} $f"
        fi
    done
}


get_packetbl_running_processes() {
	ps aux | grep $BIN | egrep -v grep >/dev/null
	if [ 0 ]; then
		PIDS=`ps aux | grep $BIN | egrep -v grep | awk '{ print $2 }'`
	fi
}


run_stop()
{
	get_packetbl_running_processes
	if [ "x$PIDS" != "x" ]; then
		kill $PIDS
	fi
		
}

run_start()
{
	get_config_files
	if [ "x$CONFIG_FILES" != "x" ]; then
		for FILE in $CONFIG_FILES
		do
			$BIN -f $FILE -p $PID_PATH
		done
	fi
}


export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$ACTION" in
  start)
	run_start
	;;
  stop)
	run_stop
	;;

  restart)
	run_stop
	run_start
	;;
  *)
	echo "Usage: /etc/init.d/packetbl {start|stop|restart}" 
	exit 1
esac

exit 0

